#include "vfnet2_export.h"
#include <QtCore/qglobal.h>
#include "vh_logging.h"

Q_DECLARE_LOGGING_CATEGORY(VEIN_NET)
Q_DECLARE_LOGGING_CATEGORY(VEIN_NET_VERBOSE)
Q_DECLARE_LOGGING_CATEGORY(VEIN_NET_TCP)
Q_DECLARE_LOGGING_CATEGORY(VEIN_NET_TCP_VERBOSE)
Q_DECLARE_LOGGING_CATEGORY(VEIN_NET_INTRO)
Q_DECLARE_LOGGING_CATEGORY(VEIN_NET_INTRO_VERBOSE)
